images: output a better error when the input image failed to load.
This is related to some build errors when one of these scripts would
fail because GIMP failed to run the input image (e.g. #16160), and we'd
get a dreaded and not obvious:

> batch command experienced a calling error:
> Traceback (most recent call last):
>   File "/path/to/_build/plug-ins/python/python-eval/python-eval.py", line 42, in code_eval
>     exec(code, globals())
>     ~~~~^^^^^^^^^^^^^^^^^
>   File "<string>", line 5, in <module>
> IndexError: list index out of range

Instead of letting the script crashing, let's verify the array of images
and print a cleaner error message.